# Generated by Django 6.0.6 on 2026-07-03 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Bloque')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Curso / División')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color_hex', models.CharField(default='#3b82f6', max_length=7, verbose_name='Color UI (Hex)')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código (Ej: 69B)')),
                ('nombre', models.CharField(max_length=150)),
                ('requiere_adjunto', models.BooleanField(default=True)),
                ('requiere_rector', models.BooleanField(default=False, verbose_name='Requiere Firma de Rector')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='Legajo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de la Inasistencia')),
                ('dia_completo', models.BooleanField(default=True, verbose_name='¿Falta todo el día?')),
                ('minutos_tarde', models.IntegerField(default=0, verbose_name='Minutos de Tardanza')),
                ('minutos_retiro', models.IntegerField(default=0, verbose_name='Minutos de Retiro Anticipado')),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Certificado/Documento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('DERIVADA', 'Derivada a Rectoría'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo (si aplica)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bloques_afectados', models.ManyToManyField(blank=True, to='licencias.bloquehorario', verbose_name='Bloques Afectados')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='licencias.docente')),
                ('tipo_licencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licencias.tipolicencia')),
            ],
        ),
        migrations.CreateModel(
            name='Suplencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de Suplencia')),
                ('fecha_fin', models.DateField(verbose_name='Fin de Suplencia')),
                ('clase_cubierta', models.BooleanField(default=False, verbose_name='¿Clase Cubierta? (Marca X)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('docente_suplente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplencias_asignadas', to='licencias.docente')),
                ('solicitud_licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplencias', to='licencias.solicitudlicencia')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.bloquehorario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='licencias.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.materia')),
            ],
            options={
                'unique_together': {('docente', 'dia_semana', 'bloque')},
            },
        ),
    ]
