# Generated by Django 6.0.7 on 2026-07-27 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquehorario',
            options={'ordering': ['numero']},
        ),
        migrations.RenameField(
            model_name='suplencia',
            old_name='solicitud_licencia',
            new_name='licencia',
        ),
        migrations.AlterUniqueTogether(
            name='horariodocente',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='solicitudlicencia',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='solicitudlicencia',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='suplencia',
            name='clase_cubierta',
        ),
        migrations.RemoveField(
            model_name='suplencia',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='suplencia',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='suplencia',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='tipolicencia',
            name='requiere_adjunto',
        ),
        migrations.RemoveField(
            model_name='tipolicencia',
            name='requiere_rector',
        ),
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MAÑANA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudlicencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudlicencia',
            name='tipo_incidencia',
            field=models.CharField(choices=[('COMPLETO', 'Día Completo'), ('TARDE', 'Llegada Tarde'), ('RETIRO', 'Retiro Anticipado'), ('BLOQUES', 'Bloques Específicos')], default='COMPLETO', max_length=10),
        ),
        migrations.AddField(
            model_name='suplencia',
            name='fecha',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suplencia',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='licencias.horariodocente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipolicencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='legajo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horariodocente',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='color_hex',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='bloques_afectados',
            field=models.ManyToManyField(blank=True, help_text='Solo si aplica a bloques específicos', to='licencias.bloquehorario'),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='dia_completo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='fecha_solicitud',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='minutos_retiro',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='minutos_tarde',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='tipo_licencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='licencias.tipolicencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suplencia',
            name='docente_suplente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplencias_realizadas', to='licencias.docente'),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
