# Generated by Django 6.0.7 on 2026-08-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_alter_bloquehorario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
