# Generated by Django 6.0.7 on 2026-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0003_docente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
