# Generated by Django 6.0.7 on 2026-09-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_docente_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudlicencia',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Hasta'),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='fecha_solicitud',
            field=models.DateField(verbose_name='Fecha Desde'),
        ),
    ]
