# Generated by Django 6.0.7 on 2026-09-16 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0005_solicitudlicencia_fecha_hasta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariodocente',
            options={'verbose_name': 'Horario Docente', 'verbose_name_plural': 'Horarios Docentes'},
        ),
        migrations.RemoveField(
            model_name='materia',
            name='color_hex',
        ),
        migrations.AddField(
            model_name='horariodocente',
            name='rol',
            field=models.CharField(choices=[('TITULAR', 'Titular / Responsable Primario'), ('CO_DOCENTE', 'Co-docente / Pareja Pedagógica'), ('JEFE_LAB', 'Jefe de Laboratorio / Apoyo Técnico')], default='TITULAR', max_length=20, verbose_name='Rol en la Clase'),
        ),
        migrations.AddField(
            model_name='horariodocente',
            name='seccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sección / Subgrupo (Ej: Grupo A, Taller 1)'),
        ),
        migrations.AddField(
            model_name='materia',
            name='tipo_modalidad',
            field=models.CharField(choices=[('CATEDRA', 'Cátedra Única (1 Docente)'), ('PAREJA', 'Pareja Pedagógica (Absorbible)'), ('TALLER', 'Taller / Laboratorio (Por Secciones)')], default='CATEDRA', max_length=20, verbose_name='Tipo de Modalidad'),
        ),
        migrations.AddField(
            model_name='suplencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suplencia',
            name='tipo_cobertura',
            field=models.CharField(choices=[('EXTERNA', 'Suplente Externo'), ('ABSORCION', 'Absorción por Pareja Pedagógica'), ('JEFE_LAB', 'Asumido por Jefe de Laboratorio')], default='EXTERNA', max_length=20, verbose_name='Tipo de Cobertura'),
        ),
        migrations.AlterField(
            model_name='horariodocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.docente'),
        ),
        migrations.AlterField(
            model_name='suplencia',
            name='docente_suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licencias.docente', verbose_name='Docente Suplente (Si aplica)'),
        ),
        migrations.AlterField(
            model_name='suplencia',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.solicitudlicencia'),
        ),
    ]
